// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gs.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetHelloWorldRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHelloWorldRequest) Reset()         { *m = GetHelloWorldRequest{} }
func (m *GetHelloWorldRequest) String() string { return proto.CompactTextString(m) }
func (*GetHelloWorldRequest) ProtoMessage()    {}
func (*GetHelloWorldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_gs_7df9d694612e4925, []int{0}
}
func (m *GetHelloWorldRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloWorldRequest.Unmarshal(m, b)
}
func (m *GetHelloWorldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloWorldRequest.Marshal(b, m, deterministic)
}
func (dst *GetHelloWorldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloWorldRequest.Merge(dst, src)
}
func (m *GetHelloWorldRequest) XXX_Size() int {
	return xxx_messageInfo_GetHelloWorldRequest.Size(m)
}
func (m *GetHelloWorldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloWorldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloWorldRequest proto.InternalMessageInfo

func (m *GetHelloWorldRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetHelloWorldResponse struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Now                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=now" json:"now,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetHelloWorldResponse) Reset()         { *m = GetHelloWorldResponse{} }
func (m *GetHelloWorldResponse) String() string { return proto.CompactTextString(m) }
func (*GetHelloWorldResponse) ProtoMessage()    {}
func (*GetHelloWorldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_gs_7df9d694612e4925, []int{1}
}
func (m *GetHelloWorldResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHelloWorldResponse.Unmarshal(m, b)
}
func (m *GetHelloWorldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHelloWorldResponse.Marshal(b, m, deterministic)
}
func (dst *GetHelloWorldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHelloWorldResponse.Merge(dst, src)
}
func (m *GetHelloWorldResponse) XXX_Size() int {
	return xxx_messageInfo_GetHelloWorldResponse.Size(m)
}
func (m *GetHelloWorldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHelloWorldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHelloWorldResponse proto.InternalMessageInfo

func (m *GetHelloWorldResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetHelloWorldResponse) GetNow() *timestamp.Timestamp {
	if m != nil {
		return m.Now
	}
	return nil
}

func init() {
	proto.RegisterType((*GetHelloWorldRequest)(nil), "pb.GetHelloWorldRequest")
	proto.RegisterType((*GetHelloWorldResponse)(nil), "pb.GetHelloWorldResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Test service

type TestClient interface {
	GetHelloWorld(ctx context.Context, in *GetHelloWorldRequest, opts ...grpc.CallOption) (*GetHelloWorldRequest, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) GetHelloWorld(ctx context.Context, in *GetHelloWorldRequest, opts ...grpc.CallOption) (*GetHelloWorldRequest, error) {
	out := new(GetHelloWorldRequest)
	err := grpc.Invoke(ctx, "/pb.Test/GetHelloWorld", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Test service

type TestServer interface {
	GetHelloWorld(context.Context, *GetHelloWorldRequest) (*GetHelloWorldRequest, error)
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_GetHelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHelloWorldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).GetHelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Test/GetHelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).GetHelloWorld(ctx, req.(*GetHelloWorldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHelloWorld",
			Handler:    _Test_GetHelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gs.proto",
}

func init() { proto.RegisterFile("gs.proto", fileDescriptor_gs_7df9d694612e4925) }

var fileDescriptor_gs_7df9d694612e4925 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x2f, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0x92, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49,
	0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24, 0xe6, 0x16,
	0x40, 0x14, 0x29, 0x69, 0x71, 0x89, 0xb8, 0xa7, 0x96, 0x78, 0xa4, 0xe6, 0xe4, 0xe4, 0x87, 0xe7,
	0x17, 0xe5, 0xa4, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25,
	0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x91, 0x5c, 0xa2, 0x68,
	0x6a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0xb1, 0x29, 0x16, 0xd2, 0xe1, 0x62, 0xce, 0xcb, 0x2f,
	0x97, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x36, 0x92, 0xd2, 0x83, 0xb8, 0x43, 0x0f, 0xe6, 0x0e, 0xbd,
	0x10, 0x98, 0x3b, 0x82, 0x40, 0xca, 0x8c, 0x7c, 0xb9, 0x58, 0x42, 0x40, 0xd6, 0xba, 0x72, 0xf1,
	0xa2, 0x58, 0x21, 0x24, 0xa1, 0x57, 0x90, 0xa4, 0x87, 0xcd, 0x85, 0x52, 0x38, 0x65, 0x94, 0x18,
	0x92, 0xd8, 0xc0, 0xf6, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xda, 0xae, 0x31, 0x0d,
	0x01, 0x00, 0x00,
}
